FUNCTION ZFI_RECONFIG_SUMATORIA.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     REFERENCE(REPORT_INPUT) TYPE  ZFI_EGRESOS_OUTPUTT
*"  EXPORTING
*"     REFERENCE(REPORT_OUTPUT) TYPE  ZFI_EGRESOS_OUTPUTT
*"----------------------------------------------------------------------
TYPES:BEGIN OF TY_BKPF,
        BUKRS	TYPE BUKRS,
        BELNR	TYPE BELNR_D,
        GJAHR	TYPE GJAHR,
        AWTYP TYPE AWTYP,
      END OF TY_BKPF,

     BEGIN OF TY_REPORT,
        BUKRS	TYPE BUKRS,
        BELNR	TYPE BELNR_D,
        GJAHR	TYPE GJAHR,
     END OF TY_REPORT.

CONSTANTS: C_AWTYP TYPE AWTYP VALUE 'RMRP'.

DATA: IT_BKPF TYPE STANDARD TABLE OF TY_BKPF,
      IT_REPORT TYPE STANDARD TABLE OF TY_REPORT WITH HEADER LINE,
      IT_REPORT_AUX TYPE STANDARD TABLE OF ZFI_EGRESOS_OUTPUT.


DATA: WA_REPORTT TYPE TY_REPORT.

LOOP AT REPORT_INPUT INTO DATA(WA_REPORT).

  WA_REPORTT-BUKRS = WA_REPORT-N_DOCUMENTO_FAC_SOCIEDAD.
  WA_REPORTT-BELNR = WA_REPORT-N_DOCUMENTO_FAC.
  WA_REPORTT-GJAHR = WA_REPORT-N_DOCUMENTO_FAC_EJERCICIO.

  APPEND WA_REPORTT TO IT_REPORT.

ENDLOOP.

DELETE ADJACENT DUPLICATES FROM IT_REPORT.

SELECT BUKRS,
       BELNR,
       GJAHR,
       AWTYP
  FROM BKPF
  INTO TABLE @IT_BKPF
  FOR ALL ENTRIES IN @IT_REPORT
  WHERE BUKRS EQ @IT_REPORT-BUKRS AND
        BELNR EQ @IT_REPORT-BELNR AND
        GJAHR EQ @IT_REPORT-GJAHR AND
        AWTYP EQ @C_AWTYP.


LOOP AT REPORT_INPUT INTO WA_REPORT.

  READ TABLE IT_BKPF TRANSPORTING NO FIELDS
  WITH KEY BUKRS = WA_REPORT-N_DOCUMENTO_FAC_SOCIEDAD
           BELNR = WA_REPORT-N_DOCUMENTO_FAC
           GJAHR = WA_REPORT-N_DOCUMENTO_FAC_EJERCICIO.

  IF SY-SUBRC EQ 0.

    COLLECT WA_REPORT INTO IT_REPORT_AUX.

  ELSE.

    APPEND WA_REPORT TO REPORT_OUTPUT.

  ENDIF.

ENDLOOP.

  IF NOT IT_REPORT_AUX IS INITIAL.

    CLEAR WA_REPORT.

    LOOP AT IT_REPORT_AUX ASSIGNING FIELD-SYMBOL(<FS_REPORT>).

      <FS_REPORT>-TOTALCARGOS = <FS_REPORT>-IMPOR_MON_L_FAC.

      APPEND <FS_REPORT> TO REPORT_OUTPUT.

    ENDLOOP.

  ENDIF.





ENDFUNCTION.
