FUNCTION ZFI_RECONFIG_SUMATORIA_2.
*"--------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     REFERENCE(REPORT_INPUT) TYPE  ZFI_EGRESOS_OUTPUTT
*"  EXPORTING
*"     REFERENCE(REPORT_OUTPUT) TYPE  ZFI_EGRESOS_OUTPUTT
*"--------------------------------------------------------------------
TYPES:BEGIN OF TY_BKPF,
        BUKRS	TYPE BUKRS,
        BELNR	TYPE BELNR_D,
        GJAHR	TYPE GJAHR,
        AWTYP TYPE AWTYP,
      END OF TY_BKPF,

     BEGIN OF TY_REPORT,
        BUKRS	TYPE BUKRS,
        BELNR	TYPE BELNR_D,
        GJAHR	TYPE GJAHR,
     END OF TY_REPORT.

CONSTANTS: C_AWTYP TYPE AWTYP VALUE 'RMRP'.

DATA: IT_BKPF TYPE STANDARD TABLE OF TY_BKPF,
      IT_REPORT TYPE STANDARD TABLE OF TY_REPORT WITH HEADER LINE,
      IT_REPORT_AUX TYPE STANDARD TABLE OF ZFI_EGRESOS_OUTPUT.


DATA: WA_REPORTT TYPE TY_REPORT.

LOOP AT REPORT_INPUT INTO DATA(WA_REPORT)..

    COLLECT WA_REPORT INTO IT_REPORT_AUX.

ENDLOOP.

  IF NOT IT_REPORT_AUX IS INITIAL.

    CLEAR WA_REPORT.

    LOOP AT IT_REPORT_AUX ASSIGNING FIELD-SYMBOL(<FS_REPORT>).

      APPEND <FS_REPORT> TO REPORT_OUTPUT.

    ENDLOOP.

  ENDIF.

ENDFUNCTION.
