*&---------------------------------------------------------------------*
*& INCLUDE          ZFI_CARGAR_CATALOGOCUENTAS_SCR
*&---------------------------------------------------------------------*

TABLES: FMGLFLEXT.

SELECTION-SCREEN BEGIN OF BLOCK SELECCION WITH FRAME TITLE TEXT-001.

  PARAMETERS: P_PATH TYPE LOCALFILE MODIF ID GP2 MEMORY ID HF,
              P_DELETE AS CHECKBOX DEFAULT ' '.

SELECTION-SCREEN END OF BLOCK SELECCION.

SELECTION-SCREEN BEGIN OF BLOCK SHOW WITH FRAME TITLE TEXT-002.

  PARAMETERS: P_SHOW AS CHECKBOX DEFAULT 'X',
              P_RBUKRS LIKE FMGLFLEXT-RBUKRS. "SOCIEDAD

  SELECT-OPTIONS: S_RYEAR  FOR FMGLFLEXT-RYEAR. "EJERCICIO

SELECTION-SCREEN END OF BLOCK SHOW.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_PATH.

  DATA(TITLE) = |SELECT EXCEL FILE, E.G. *.XLSX|.
  DATA(DEFAULTEXTENSION) = |.XLSX|.
  DATA(FILEFILTER) = `EXCEL FILES (*.XLSX)|*.XLSX`.
  DATA IT_TAB TYPE FILETABLE.
  DATA RETURNCODE TYPE I.

  CALL METHOD CL_GUI_FRONTEND_SERVICES=>FILE_OPEN_DIALOG
    EXPORTING
      WINDOW_TITLE      = TITLE
      DEFAULT_EXTENSION = DEFAULTEXTENSION
*     DEFAULT_FILENAME  =
*     FILE_FILTER       = FILEFILTER
*     WITH_ENCODING     =
*     INITIAL_DIRECTORY =
*     MULTISELECTION    =
    CHANGING
      FILE_TABLE        = IT_TAB
      RC                = RETURNCODE
*     USER_ACTION       =
*     FILE_ENCODING     =
*    EXCEPTIONS
*     FILE_OPEN_DIALOG_FAILED = 1
*     CNTL_ERROR        = 2
*     ERROR_NO_GUI      = 3
*     NOT_SUPPORTED_BY_GUI    = 4
*     OTHERS            = 5
    .
  IF SY-SUBRC <> 0.
*   IMPLEMENT SUITABLE ERROR HANDLING HERE
  ENDIF.

  READ TABLE IT_TAB ASSIGNING FIELD-SYMBOL(<SELECTEDFILENAME>) INDEX 1.
  IF SY-SUBRC = 0.
    P_PATH = <SELECTEDFILENAME>-FILENAME.
  ENDIF.
